import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import axios from 'axios';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import './styles.css';

const API = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:4000' });
const AuthContext = createContext(null);
const demoApplicant = { AMT_INCOME_TOTAL: 120000, AMT_CREDIT: 420000, AMT_ANNUITY: 28000, DAYS_BIRTH: -12500, DAYS_EMPLOYED: -2400, NAME_INCOME_TYPE: 'Working', NAME_EDUCATION_TYPE: 'Higher education', CODE_GENDER: 'F' };
function useAuth() { return useContext(AuthContext); }
function AuthProvider({ children }) { const [session, setSession] = useState(null); const login = async (path, body) => { const { data } = await API.post(path, body); setSession(data); }; const logout = () => setSession(null); return <AuthContext.Provider value={{ session, login, logout }}>{children}</AuthContext.Provider>; }
function Shell({ page, setPage, children }) { const { session, logout } = useAuth(); return <div className="app"><aside><div className="brand"><span>AR</span><div>Atlas Risk<small>Finance intelligence</small></div></div><nav>{[['dashboard','Overview'],['check','Applicant check'],['stress','Stress lab'],['history','Reports']].map(([id,label]) => <button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}><i>{id==='dashboard'?'◈':id==='check'?'＋':id==='stress'?'◌':'▤'}</i>{label}</button>)}</nav><div className="side-foot"><div className="live-dot"/>Model online<strong>v1.0 / LightGBM</strong></div></aside><main><header><div><span className="eyebrow">PORTFOLIO / 23 AUG 2026</span><h1>{page==='dashboard'?'Risk overview':page==='check'?'Applicant risk check':page==='stress'?'Stress lab':'Report history'}</h1></div>{session && <button className="profile" onClick={logout}>{session.user?.name || 'Analyst'} <span>↗</span></button>}</header>{children}</main></div> }
function Score({ value=0.24 }) { return <div className="score"><div className="score-ring" style={{'--score':`${value*100}%`}}><strong>{Math.round(value*100)}<small>%</small></strong></div><div><span className="eyebrow">DEFAULT PROBABILITY</span><h2 className={value>=.5?'danger':'good'}>{value>=.5?'High risk':'Low risk'}</h2><p>Model confidence is stable</p></div></div> }
function Dashboard({ setPage }) { return <><section className="stats"><div><span>Portfolio exposure</span><strong>$18.4M</strong><em>↘ 2.4% this month</em></div><div><span>Avg. default probability</span><strong>18.6%</strong><em>↘ 1.8% vs last quarter</em></div><div><span>Active assessments</span><strong>1,284</strong><em>↗ 14.2% this month</em></div></section><section className="grid"><div className="panel heat"><div className="panel-title"><div><span className="eyebrow">EXPOSURE MAP</span><h3>Portfolio risk by segment</h3></div><span className="tag">LIVE MODEL</span></div><div className="heatmap">{['Prime','Near prime','Growth','Emerging','SME','Consumer'].map((x,i)=><div className="heat-cell" key={x} style={{'--heat':`${20+i*12}%`}}><b>{x}</b><strong>{[8,14,22,31,38,47][i]}%</strong><small>{['$4.8M','$3.2M','$2.7M','$1.9M','$3.8M','$2.0M'][i]}</small></div>)}</div></div><div className="panel signal"><span className="eyebrow">MODEL SIGNAL</span><h3>Healthy book, watch emerging</h3><p>Risk concentration is shifting toward newer borrowers. Run an applicant check to explore individual drivers.</p><button className="primary" onClick={()=>setPage('check')}>Start assessment <span>→</span></button></div></section><section className="bottom-row"><div className="panel"><div className="panel-title"><h3>Recent assessments</h3><button className="text-btn" onClick={()=>setPage('history')}>View all →</button></div><ReportRows compact/></div><div className="panel methodology"><span className="eyebrow">MODEL NOTES</span><h3>Explainable by design</h3><p>Every score pairs a calibrated probability with its strongest SHAP contributions, so decisions remain reviewable.</p><div className="mini-rule"><span style={{width:'82%'}}/></div><small>ROC-AUC <b>0.742</b></small></div></section></> }
function ReportRows({compact=false, items=[['Maya Chen','Low risk','18.4%','Today'],['Jordan Ellis','Low risk','27.1%','Yesterday'],['N. Patel','High risk','63.8%','18 Aug']].slice(0,compact?3:10)}) { return <div className="reports">{items.map((r,i)=><div className="report" key={i}><span className="avatar">{r[0].split(' ').map(x=>x[0]).join('')}</span><b>{r[0]}</b><span className={r[1]==='High risk'?'danger':'good'}>{r[1]}</span><strong>{r[2]}</strong><small>{r[3]}</small></div>)}</div> }
function Login() { const { login } = useAuth(); const [signup,setSignup]=useState(false); const [form,setForm]=useState({name:'',email:'analyst@atlas.finance',password:'demo123'}); return <div className="auth"><div className="auth-mark">AR</div><span className="eyebrow">ATLAS RISK / FINANCE INTELLIGENCE</span><h1>Make risk<br/><i>legible.</i></h1><p>Decision intelligence for lending teams who need to move with clarity.</p><form onSubmit={e=>{e.preventDefault();login(signup?'/api/auth/signup':'/api/auth/login',form)}}>{signup&&<input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input placeholder="Work email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary">{signup?'Create account':'Enter workspace'} <span>→</span></button></form><button className="text-btn" onClick={()=>setSignup(!signup)}>{signup?'Already have an account? Sign in':'New to Atlas? Create an account'}</button></div> }
function Check({ stress=false }) { const { session }=useAuth(); const [form,setForm]=useState(demoApplicant); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [rate,setRate]=useState(0); const submit=async()=>{setLoading(true);try{const {data}=await API.post(stress?'/api/risk/stress-test':'/api/risk/predict',stress?{data:form,rate_hike_pct:rate}:form,{headers:{Authorization:`Bearer ${session.token}`}});setResult(data)}finally{setLoading(false)}}; useEffect(()=>{if(stress)submit()},[rate]); return <section className="check-layout"><div className="panel form-panel"><div className="panel-title"><div><span className="eyebrow">BORROWER PROFILE</span><h3>{stress?'Macro shock parameters':'Applicant financial data'}</h3></div></div>{stress&&<label className="slider-label">Interest rate hike <b>+{rate.toFixed(1)}%</b><input type="range" min="0" max="12" step=".5" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label>}<div className="fields">{[['AMT_INCOME_TOTAL','Annual income'],['AMT_CREDIT','Credit requested'],['AMT_ANNUITY','Annual annuity'],['DAYS_BIRTH','Days since birth'],['DAYS_EMPLOYED','Days employed']].map(([key,label])=><label key={key}>{label}<input type="number" value={form[key]} onChange={e=>setForm({...form,[key]:Number(e.target.value)})}/></label>)}</div>{!stress&&<button className="primary" onClick={submit} disabled={loading}>{loading?'Scoring...':'Assess default risk'} <span>→</span></button>}</div><div className="panel result-panel"><span className="eyebrow">ASSESSMENT RESULT</span>{result?<><Score value={result.risk_score}/><h3>Why this score?</h3><ResponsiveContainer width="100%" height={190}><BarChart data={result.top_factors} layout="vertical" margin={{left:10,right:20}}><XAxis type="number" hide/><YAxis type="category" dataKey="feature" width={125} tick={{fill:'#98a09d',fontSize:11}}/><Tooltip contentStyle={{background:'#202727',border:'1px solid #3b4743'}}/><Bar dataKey="impact" radius={[0,3,3,0]}>{result.top_factors.map((x,i)=><Cell key={i} fill={x.impact>0?'#e07a5f':'#71b7a3'}/>)}</Bar></BarChart></ResponsiveContainer><p className="caption">Positive impact increases default likelihood. Negative impact reduces it.</p></>:<div className="empty"><div>◎</div><h3>Awaiting applicant data</h3><p>Submit a profile to reveal the model's reasoning.</p></div>}</div></section> }
function App(){const {session}=useAuth();const [page,setPage]=useState('dashboard');if(!session)return <Login/>;return <Shell page={page} setPage={setPage}>{page==='dashboard'?<Dashboard setPage={setPage}/>:page==='history'?<div className="panel history-panel"><span className="eyebrow">AUDIT TRAIL</span><h3>Past risk reports</h3><ReportRows/></div>:<Check stress={page==='stress'}/>}</Shell>};
createRoot(document.getElementById('root')).render(<AuthProvider><App/></AuthProvider>);
